### ISSUE TITLE
Can no longer login?

### ISSUE THREAD

**Issue by lukemunn** [atlarge-research/opendc-simulator#45]
I experimented with OpenDC last year and setup a couple projects, but the login no longer seems to work? 

Clicking 'Login with Google' in the top right opens the popup window and prompts for G username and pass, but open entering them, popup disappears but Login button remains unchanged and no new options show up. Am I missing something here or has there been a change? 

Would love to use the online version because the port forwarding on the Docker version seems tricky! :-)

**Comment by gandreadis** [comment]
Hi @lukemunn, thanks so much for reaching out! The login indeed didn't work, that was an error on our side. It should now be fixed, could you try logging in again (with Chrome)?

Aside, on the port forwarding: I understand if this can seem daunting, let us know if there is anything we can do to make it more straight-forward!

**Comment by lukemunn** [comment]
Yes, login works again. Thanks for the quick fix.
