### ISSUE TITLE
Docker build failure

### ISSUE THREAD

**Issue by fabianishere** [atlarge-research/opendc-simulator#6]
The Docker image provided in the repository fails to build due file permission errors.

![pasted image at 2017_09_29 03_08 pm](https://user-images.githubusercontent.com/767351/31053433-54779d5a-a69d-11e7-9ff5-28bfe81f6434.png)

**Comment by gandreadis** [comment]
Actually, while the screenshot was taken in a Windows environment, this was encountered on a Linux system (Ubuntu). It's a PuTTY session with SSH, so only the client is on Windows

**Comment by fabianishere** [comment]
I updated the issue. This may be related to https://github.com/moby/moby/issues/24660.

**Comment by fabianishere** [comment]
@gandreadis Do you know what version of Docker the server is running?

**Comment by gandreadis** [comment]
@fabianishere Just checked: It's docker version 1.13.1

**Comment by fabianishere** [comment]
I am unable to reproduce the problem on either 1.12 or 1.13 on Ubuntu 16.04 with the current master.
